# Indices

In [24]:
import numpy as np

In [25]:
numeros = np.arange(11)**2

In [26]:
numeros

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [27]:
indices = [2,5,7]


In [29]:
numeros[indices]

array([ 4, 25, 49], dtype=int32)

In [30]:
arreglo_frutas = np.array([
    ['Piña','Manzana','Pera','Melon'],
    ['Pera','Uva','Naranja','Papaya'],
    ['Frutilla','Platano','Granadilla','Sandia']
])

In [31]:
arreglo_frutas.shape

(3, 4)

In [39]:
arreglo_filas = np.array([
    [0,0],
    [1,1],
    [2,2],
])

In [40]:
arreglo_columnas = np.array([
    [1,3],
    [1,2],
    [0,2],
])

In [41]:
arreglo_frutas[arreglo_filas,arreglo_columnas]

array([['Manzana', 'Melon'],
       ['Uva', 'Naranja'],
       ['Frutilla', 'Granadilla']], dtype='<U10')

In [35]:
arreglo_frutas

array([['Piña', 'Manzana', 'Pera', 'Melon'],
       ['Pera', 'Uva', 'Naranja', 'Papaya'],
       ['Frutilla', 'Platano', 'Granadilla', 'Sandia']], dtype='<U10')

In [63]:
arreglo_filas1 = np.array([
    [1,2],
    [1,1],
    [2,2],
])

In [64]:
arreglo_columnas = np.array([
    [2,3],
    [2,3],
    [2,3],
])

In [ ]:
arreglo_frutas[arreglo_filas,arreglo_columnas]

In [73]:
arreglo_frutas1 = np.array([
    [['Piña','Manzana'],['Pera','Melon'],['Pera','Uva'],['Naranja','Papaya']],
    [['Frutilla','Platano'],['Granadilla','Sandia'],['Piña2','Manzana2'],['Pera2','Melon2']],
    [['Pera2','Uva2'],['Naranja2','Papaya2'],['Frutilla2','Platano2'],['Granadilla2','Sandia2']]
])

In [75]:
arreglo_frutas1.shape

(3, 4, 2)

In [110]:
arreglo_frutas2 = np.array([
    [['Piña','Manzana'],['Pera','Melon'],['Pera','Uva']],
    [['Naranja','Papaya'],['Frutilla','Platano'],['Granadilla','Sandia']],
    [['Piña2','Manzana2'],['Pera2','Melon2'],['Pera2','Uva2']],
    [['Naranja2','Papaya2'],['Frutilla2','Platano2'],['Granadilla2','Sandia2']]
])

In [111]:
arreglo_frutas2.shape

(4, 3, 2)

In [189]:
arreglo_frutas1

'P'

In [144]:
arreglo_frutas1[0][3][1]

'Papaya'

In [ ]:
arreglo_filas1 = np.array([
    [0],[0],[0],
    [1],[0],[0],
    [2],[0],[0]
   
])

In [145]:
arreglo_columnas1 = np.array([
    [0],[3],[1],
    [1],[3],[1],
    [2],[3],[1]
   
])

In [173]:
arreglo_frutas1[[np.array([0,0]),np.array([0,0]),np.array([0,0])],[np.array([1]),np.array([1]),np.array([1])]]

array([[['Pera', 'Melon'],
        ['Pera', 'Melon']],

       [['Pera', 'Melon'],
        ['Pera', 'Melon']],

       [['Pera', 'Melon'],
        ['Pera', 'Melon']]], dtype='<U11')

In [150]:
arreglo_frutas1[np.array([0,0]),np.array([0,0]),np.array([0,1])]

array(['Piña', 'Manzana'], dtype='<U11')

In [174]:
arreglo_diez = np.arange(10)

In [175]:
arreglo_mayor_a_cinco = arreglo_diez > 5

In [176]:
arreglo_diez[arreglo_mayor_a_cinco]

array([6, 7, 8, 9])

In [2]:
arreglo_frutas1

NameError: name 'arreglo_frutas1' is not defined

'P'