In [1]:
import numpy as np

In [2]:
type([1,2,3])

list

In [3]:
arreglo_np = np.array([1,2,3])

In [4]:
type(arreglo_np)

numpy.ndarray

In [6]:
tupla_np = np.array((1,2,3,4))

In [7]:
np.zeros((5))

array([0., 0., 0., 0., 0.])

In [8]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [10]:
np.zeros([5,2,3])

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [11]:
np.ones((3,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [15]:
np.empty((3,4,5))

array([[[2.39242652e-314, 2.24276900e-314, 2.39242594e-314,
         2.24276900e-314, 2.39242699e-314],
        [2.24276900e-314, 2.39242724e-314, 2.24276900e-314,
         2.39242636e-314, 2.24276900e-314],
        [2.39242674e-314, 2.24251515e-314, 2.24276900e-314,
         2.39438447e-314, 2.24254720e-314],
        [2.39242663e-314, 2.24276900e-314, 2.39438418e-314,
         2.24254720e-314, 2.39242600e-314]],

       [[2.24276900e-314, 2.39438304e-314, 2.24254720e-314,
         2.24254897e-314, 2.39595311e-314],
        [2.24254720e-314, 2.24295429e-314, 2.24254897e-314,
         2.30197086e-314, 2.24254720e-314],
        [2.37941312e-314, 2.24276900e-314, 2.37941318e-314,
         2.24254720e-314, 2.37941240e-314],
        [2.24276900e-314, 2.38880162e-314, 2.24254720e-314,
         2.39547193e-314, 2.24276900e-314]],

       [[2.39547235e-314, 2.24254720e-314, 2.39438311e-314,
         2.24254900e-314, 2.24276900e-314],
        [2.24254897e-314, 2.39547271e-314, 2.24254720e-314,


In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(3,10,2)

array([3, 5, 7, 9])

In [24]:
arreglo_pares = np.arange(0,20,2)
print (arreglo_pares)

[ 0  2  4  6  8 10 12 14 16 18]


In [25]:
arreglo_pares.size

10

In [27]:
arreglo_pares.shape

(10,)

In [28]:
arreglo_pares.reshape((5,2))

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [29]:
np.arange(24).reshape((6,2,2))

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23]]])

In [31]:
np.arange(10000)

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [33]:
np.arange(100000).reshape(10000,10)

array([[    0,     1,     2, ...,     7,     8,     9],
       [   10,    11,    12, ...,    17,    18,    19],
       [   20,    21,    22, ...,    27,    28,    29],
       ...,
       [99970, 99971, 99972, ..., 99977, 99978, 99979],
       [99980, 99981, 99982, ..., 99987, 99988, 99989],
       [99990, 99991, 99992, ..., 99997, 99998, 99999]])

In [37]:
a = np.array([10,10,10])
b = np.array((5,5,5))

In [38]:
# Suma
a+b

array([15, 15, 15])

In [40]:
# Resta
a-b

array([5, 5, 5])

In [41]:
# Multiplicacion
a*b

array([50, 50, 50])

In [42]:
# Dividir
a/b

array([2., 2., 2.])

In [44]:
a % 2

array([0, 0, 0])

In [45]:
a + 10

array([20, 20, 20])

In [46]:
a - 3

array([7, 7, 7])

In [47]:
a * 2

array([20, 20, 20])

In [50]:
arreglo_doce = np.arange(12)
arreglo_doce

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [49]:
arreglo_doce > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True])

In [52]:
A = np.arange(4).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [53]:
B = np.arange(4,8).reshape(2,2)
B

array([[4, 5],
       [6, 7]])

In [54]:
A*B

array([[ 0,  5],
       [12, 21]])

In [55]:
A.dot(B)

array([[ 6,  7],
       [26, 31]])

In [56]:
np.dot(A,B)

array([[ 6,  7],
       [26, 31]])

In [61]:
RESULTADO = np.arange(4).reshape(2,2)
np.dot(A,B,RESULTADO)

array([[ 6,  7],
       [26, 31]])

In [62]:
arreglo_tres = np.arange(3)
arreglo_tres +=2

In [63]:
arreglo_tres

array([2, 3, 4])

In [64]:
arreglo_tres.sum()

9

In [65]:
arreglo_tres.min()

2

In [66]:
arreglo_tres.max()

4

In [74]:
arreglo_tres_cuatro = np.arange(24).reshape(6,2,2)
arreglo_tres_cuatro

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23]]])

In [72]:
arreglo_tres_cuatro.sum(axis=0)

array([12, 15, 18, 21])

In [73]:
arreglo_tres_cuatro.sum(axis=1)

array([ 6, 22, 38])

In [75]:
arreglo_tres_cuatro.sum(axis=2)

array([[ 1,  5],
       [ 9, 13],
       [17, 21],
       [25, 29],
       [33, 37],
       [41, 45]])