# Tienda de Computadores

La empresa CompuTienda se encarga de la fabricación de equipos electrónicos en los siguientes modelos: Computadores de escritorio, Computadores portátiles, impresoras.

La producción mensual en la empresa ha sido catalogada de la siguiente manera.
Equipos de alta calidad (A)
Equipos de mediana calidad (B)
Equipos económicos (C)
Cada mes el reporte de ventas indica que se vendió lo siguiente:
52 Impresoras de(C)
69 Computadores Portátiles de(C)
45 Computadores de Ecritorio de(C)
35 Impresoras de (B)
50 Computadores Portátiles de (B)
28 Computadores de Escritorio de(B)}
19 Impresoras de (A)
23 Computadores Portátiles de(A)
15 Computadores de Escritorio de (A)

1)Colocar el logo de la empresa

In [7]:
import numpy as np

In [49]:
from PIL import Image
imagen = Image.open("./Computador.png")
imagen.show()

2)Girar la imagen a 90 grados

In [36]:
from PIL import Image
imagen = Image.open("./Computador.png")
imagenrotate = imagen.rotate(-90)
imagenrotate.show()

3)Colocar el slogan de la empresa

In [74]:
from PIL import Image
from PIL import ImageDraw
from PIL import ImageFont
imagen = Image.open("./Computador.png")
draw = ImageDraw.Draw(imagen)
font = ImageFont.truetype("verdana.ttf",40)
draw.text((0.1,0.1), "La mejor tecnología al mejor precio", fill = "black", font =font)
imagen.show()

4)Representación del problema en matriz

En el eje i se representan los dispositivos electrónicos y en el eje j calidad

In [133]:
produccion_mensual = np.array([52,69,45,35,50,28,19,23,15]).reshape(3,3)
print(produccion_mensual)

[[52 69 45]
 [35 50 28]
 [19 23 15]]


5)Calculo de la producción semestral y anual

In [134]:
produccion_semestral = produccion_mensual * 6 #Producción Semestral
print(f"La produccion semestral es:\n{produccion_semestral}")
print("\n")
produccion_anual = produccion_mensual * 12  #Producción Anual
print(f"La produccion anual es:\n{produccion_anual}")

La produccion semestral es:
[[312 414 270]
 [210 300 168]
 [114 138  90]]


La produccion anual es:
[[624 828 540]
 [420 600 336]
 [228 276 180]]


6)Los precios de los productos son los siguientes. Impresora(C) 150 dólares, Computadores portátiles(C) 450 dólares, computadores de escritorio(C) 7500 dólares. Los precios de los productos restantes se Aumentan según la calidad en 900 dólares.

In [135]:
precios = np.arange(9)
for i in np.nditer(precios, order="F", op_flags=["readwrite"]):
    i[...] = ((i%1 + 1) * 300) * (i + 0.5)
precios = precios.reshape((3,3)).T
print(precios)

[[ 150 1050 1950]
 [ 450 1350 2250]
 [ 750 1650 2550]]


7)Calcular la venta anual de acuerdo a la producción anual

In [136]:
ventas_anual = produccion_anual * precios
print(ventas_anual)

[[  93600  869400 1053000]
 [ 189000  810000  756000]
 [ 171000  455400  459000]]


8)Calcular venta total anual

In [137]:
print(ventas_anual.sum())

4856400


9)Calcular el promedio de comprar computador, laptop e impresora de A, de B y de C

In [141]:
print(np.mean(precios, axis=0))

[ 450. 1350. 2250.]


9)Calcular la mediana de comprar computador, laptop e impresora de A, de B y de C

In [142]:
print(np.median(precios, axis=0))

[ 450. 1350. 2250.]


10)Desviacion Estandar 

In [143]:
print(np.std(precios, axis=0))

[244.94897428 244.94897428 244.94897428]


11 Varianza

In [144]:
print(np.var(precios, axis=0))

[60000. 60000. 60000.]


# Ejercicio con sen 

Se tiene el siguiente triángulo. Hallar las variables restantes.

In [150]:
from PIL import Image
imagen = Image.open("./Triangulo.png")
imagen.show()

1)Calculo de c(hipotenusa)

In [155]:
import math
altura = 20
base = 23 
c = math.sqrt(((20)**2) + ((23)**2))
print(f"El valor de la hipotenusa es:\n{c}")

El valor de la hipotenusa es:
30.479501308256342


2)Calculo del ángulo alfa

In [167]:
angulo_alfa = math.asin((20/c))
angulo_alfa_grados = math.degrees(angulo_alfa) 
print(f"El valor del angulo alfa es:\n{angulo_alfa_grados}")

El valor del angulo alfa es:
41.00908690157022


3)Calculo del angulo restante

In [169]:
angulo_restante = 180-90-angulo_alfa_grados
print(f"El valor del angulo restante es:\n{angulo_restante}")

El valor del angulo restante es:
48.99091309842978


4)Imagen de Resultados

In [170]:
from PIL import Image
imagen = Image.open("./Triangulo_completo.png")
imagen.show()